---
- hosts: all
  connection: local
  name: Add User
  gather_facts: False

  tasks:

  # When adding a user, it must be enabled afterwards
  - name: Add user
    redfish_command:
      category: Accounts
      command: AddUser
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
      userid: "{{ userid }}"
      username: "{{ username }}"
      userpswd: "{{ userpswd }}"
      userrole: "{{ userrole }}"
