---
  - name: Assert forceoff variable
    assert:
      that:
        - forceoff is defined
      fail_msg: "The variable forceoff is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable forceoff is defined"
    run_once: true

  - debug:
      msg: "forceoff is {{ forceoff }}"
    when: forceoff is defined
    run_once: true

  - name: Assert poweroff_countdown variable
    assert:
      that:
        - poweroff_countdown is defined
      fail_msg: "The variable poweroff_countdown is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable poweroff_countdown is defined"
    run_once: true

  - debug:
      msg: "poweroff_countdown is {{ poweroff_countdown }} SECONDS"
    when: poweroff_countdown is defined
    run_once: true

  - name: Assert activating_countdown variable
    assert:
      that:
        - activating_countdown is defined
      fail_msg: "The variable activating_countdown is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable activating_countdown is defined"
    run_once: true

  - debug:
      msg: "activating_countdown is {{ activating_countdown }} SECONDS"
    when: activating_countdown is defined
    run_once: true

  - name: Assert poweroff_maxretries variable
    assert:
      that:
        - poweroff_maxretries is defined
      fail_msg: "The variable poweroff_maxretries is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable poweroff_maxretries is defined"
    run_once: true

  - debug:
      msg: "poweroff_maxretries is {{ poweroff_maxretries }}"
    when: poweroff_maxretries is defined
    run_once: true

  - name: Assert activating_maxretries variable
    assert:
      that:
        - activating_maxretries is defined
      fail_msg: "The variable activating_maxretries is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable activating_maxretries is defined"
    run_once: true

  - debug:
      msg: "activating_maxretries is {{ activating_maxretries }}"
    when: activating_maxretries is defined
    run_once: true

