---

  - name: Wait until success power off
    block:
      - name: Set the retry counter
        set_fact:
          retry_power_off_count: "{{ 0 if retry_power_off_count is undefined else retry_power_off_count|int + 1 }}"
        
      - name: Get Power
        include_tasks: utils_get_power.yml

      - debug:
          msg: "Power ({{ power }})"
          verbosity: 2

      - set_fact:
          found_retry_power_off: False

      - set_fact:
          found_retry_power_off: True
        when: power == "xyz.openbmc_project.State.Host.HostState.Off"

      - name: Pause {{ poweroff_countdown }}s while host is not powered off
        pause:
          seconds: "{{ poweroff_countdown }}"
        when: found_retry_power_off is defined and found_retry_power_off == False

      - fail:
          msg: "Not Powered off"
        when: found_retry_power_off is defined and found_retry_power_off == False

    rescue:
      - fail:
          msg: Ended after {{ poweroff_maxretries }} retries
        when: retry_power_off_count|int == poweroff_maxretries|int

      - name: Powering off
        debug:
          msg: "Powering off... 1 / {{ poweroff_maxretries }} "
        when: retry_power_off_count|int == 1

      - name: Retrying Powering off
        debug:
          msg: "Retrying check for power off... {{ retry_power_off_count }} / {{ poweroff_maxretries }}  "
        when: retry_power_off_count|int > 1

      - include_tasks: wait_until_success_power_off.yml



