version: '3.6'
services:
  nodered:
    build: nodered/.
    container_name: nodered
    expose:
      - 1880
#    network_mode: host 
    ports: 
      - 1880:1880
    environment:
      HTTP_PROXY: http://193.56.47.8:8080/
      HTTPS_PROXY: http://193.56.47.8:8080/
      NO_PROXY: 127.0.0.1,rabbitmq,zabbix,awx, awx_web, awx_task,localhost,elasticsearch,kibana,logstash,filebeat,metricbeat,heartbeat,auditbeat,grafana,prometheus,nodeexporter,nodered, caddy,cadvisor,alertmanage,172.31.130.224,172.31.60.18,172.31.92.239,172.31.100.156,172.31.60.18,172.31.92.249,172.31.92.222,172.31.92.44,172.31.92.34
    volumes:
      - ./nodered/data:/data:rw      
    restart: always


