version: '3.6'
services:
  zabbix-server:
    image: bullsequana-edge-system-management_zabbix-server:${MISM_BULLSEQUANA_EDGE_VERSION}
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-zabbix.${MISM_TAG_BULLSEQUANA_EDGE_VERSION}
    ports:
      - 10051:10051
    expose: 
      - 10051
    user: root
    privileged : true
    restart: unless-stopped       
    container_name: zabbix-server
    hostname: zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/server/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - ./zabbix/server/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - ./zabbix/agent/zabbix_agentd.psk:/etc/zabbix/zabbix_agentd.psk:ro
      - /var/log/rsyslog:/var/log/zabbix/rsyslog:rw
#     - ./zabbix/dockerdata/server/modules:/var/lib/zabbix/modules
#     - ./zabbix/zabbix_server.conf:/etc/zabbix/zabbix_server.conf
    depends_on:
      - zabbix-postgres
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      PHP_TZ: ${timezone}

  zabbix-web:
    image: bullsequana-edge-system-management_zabbix-web:${MISM_BULLSEQUANA_EDGE_VERSION}
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-zabbix-web.${MISM_TAG_BULLSEQUANA_EDGE_VERSION}
    restart: unless-stopped    
    container_name: zabbix-web
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      PHP_TZ: ${timezone}
    ports:
      - 4443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/ssl:/etc/ssl/nginx:ro
    user: root
    depends_on:
      - zabbix-server
    links:
      - zabbix-server:zabbix-server
  
  zabbix-agent:
    image: bullsequana-edge-system-management_zabbix-agent:${MISM_BULLSEQUANA_EDGE_VERSION}
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-zabbix-agent.${MISM_TAG_BULLSEQUANA_EDGE_VERSION}
    ports:
      - 10050:10050
    expose: 
      - 10050
    user: root
    privileged : true
    depends_on:
      - zabbix-server
    restart: unless-stopped
    container_name: zabbix-agent
    hostname: zabbix-agent
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      PHP_TZ: ${timezone}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log/rsyslog:/var/log/zabbix/rsyslog:rw
      - ./zabbix/agent/zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf:Z
      - ./zabbix/agent/zabbix_agentd.psk:/etc/zabbix/zabbix_agentd.psk:Z
#      - ./zabbix/agent/zabbix_agentd.userparams.conf:/etc/zabbix/zabbix_agentd.d/zabbix_agentd.userparams.conf:Z
#      - ./zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
#      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
#      - ./zabbix/agent/modules:/var/lib/zabbix/modules
      - ./zabbix/agent/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
    links:
      - zabbix-server:zabbix-server

  zabbix-postgres:
    image: postgres:${POSTGRES_ZABBIX_BULLSEQUANA_EDGE_VERSION}
    container_name: zabbix-postgres
    hostname: zabbix-postgres
    restart: unless-stopped
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PHP_TZ: ${timezone}
    ports:
      - 5555:5432
    expose: 
      - 5555
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/pgdata:/var/lib/postgresql/data/pgdata:Z
