version: '3.6'
services:

  awx_web:
    image: bullsequana-edge-system-management_awx_web:${MISM_BULLSEQUANA_EDGE_VERSION}
    build: 
      context: Dockerfiles
      dockerfile: Dockerfile-awx_web.${MISM_TAG_BULLSEQUANA_EDGE_VERSION}
    container_name: awx_web
    depends_on:
      - rabbitmq
      - memcached
      - awx_postgres
    ports:
      - "443:8052"
    hostname: awx_web
    user: root
    restart: always
    volumes:
      - ./ansible/playbooks:/var/lib/awx/projects:rw
      - ./ansible/inventory:/var/lib/awx/inventory:rw
#      - ./ansible/inventory:/etc/ansible:rw
      - ./ansible/vars:/etc/ansible/vars:rw
#      - ./ansible/vars:/var/lib/awx/inventory/vars:rw
#      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml:/usr/lib/python3.6/site-packages/ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml
#      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml:/usr/share/ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml
#      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.py:/usr/lib/python3.6/site-packages/ansible/plugins/inventory/redfish_plugin_ansible_inventory.py
#      - ./ansible/plugins/inventory/:/usr/share/ansible/plugins/inventory
      - ./ansible/plugins/callback/ansible_stdout_compact_logger:/usr/share/ansible/plugins/callback/ansible_stdout_compact_logger
#      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc.py:/usr/lib/python3.6/site-packages/ansible/modules/remote_management/openbmc/atos_openbmc.py:ro
#      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/lib/python3.6/site-packages/ansible/module_utils/atos_openbmc_utils.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc.py:/usr/share/ansible/plugins/modules/atos_openbmc.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/share/ansible/plugins/module_utils/atos_openbmc_utils.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/share/ansible/plugins/modules/__init__.py:ro
      - ./ansible/awx-ssl:/var/lib/awx-ssl:rw
      - /:/host:ro
    env_file:
      - Dockerfiles/ansible.env

  awx_task:
    image: bullsequana-edge-system-management_awx_task:${MISM_BULLSEQUANA_EDGE_VERSION}
    build: 
      context: Dockerfiles
      dockerfile: Dockerfile-awx_task.${MISM_TAG_BULLSEQUANA_EDGE_VERSION}
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - awx_web
      - awx_postgres
    # command: ["/var/lib/awx/projects/add_playbooks.py", "/var/lib/awx/projects/playbooks.yml"]
    hostname: awx
    user: root
    restart: always
    volumes:
      - ./ansible/playbooks:/var/lib/awx/projects:rw
      - ./ansible/inventory:/var/lib/awx/inventory:rw
#      - ./ansible/inventory:/etc/ansible:rw
      - ./ansible/vars:/etc/ansible/vars:rw
#      - ./ansible/vars:/var/lib/awx/inventory/vars:rw
#      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml:/usr/share/ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml
#      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.py:/usr/lib/python3.6/site-packages/ansible/plugins/inventory/redfish_plugin_ansible_inventory.py
#      - ./ansible/plugins/inventory/:/usr/share/ansible/plugins/inventory
      - ./ansible/plugins/callback/ansible_stdout_compact_logger:/usr/share/ansible/plugins/callback/ansible_stdout_compact_logger
#      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc.py:/usr/lib/python3.6/site-packages/ansible/modules/remote_management/openbmc/atos_openbmc.py:ro
#      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/lib/python3.6/site-packages/ansible/module_utils/atos_openbmc_utils.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc.py:/usr/share/ansible/plugins/modules/atos_openbmc.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/share/ansible/plugins/module_utils/atos_openbmc_utils.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/share/ansible/plugins/modules/__init__.py:ro
      - ./ansible/awx-ssl:/var/lib/awx-ssl:rw
      - /:/host:ro
    env_file:
      - Dockerfiles/ansible.env

  rabbitmq:
    image: rabbitmq:${RABBITMQ_AWX_BULLSEQUANA_EDGE_VERSION}
    container_name: awx_rabbitmq
    restart: always
    hostname: rabbitmq
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672    
    env_file:
      - Dockerfiles/ansible.env

  memcached:
    image: memcached:${MEMCACHED_AWX_BULLSEQUANA_EDGE_VERSION}
    container_name: awx_memcached
    restart: always

  awx_postgres:
    image: postgres:${POSTGRES_AWX_BULLSEQUANA_EDGE_VERSION}
    container_name: awx_postgres
    hostname: awx_postgres
    restart: always
    ports:
      - 5432:5432
    expose: 
      - 5432
    volumes:
      - ./ansible/pgdata:/var/lib/postgresql/data/pgdata:Z
    env_file:
      - Dockerfiles/ansible.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_AWX_BULLSEQUANA_EDGE_VERSION}
    container_name: pgadmin
    depends_on:
      - awx_postgres
    user: root
    restart: always
    ports:
      - 7070:80
    volumes:
      - ./ansible/pgadmin:/var/lib/pgadmin/storage:Z
    env_file:
      - Dockerfiles/ansible.env

