version: '3.6'
services:
  zabbix-server:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-zabbix
      args:
        MISM_BULLSEQUANA_EDGE_VERSION: ${MISM_BULLSEQUANA_EDGE_VERSION}
    ports:
      - 10051:10051
    expose: 
      - 10051
    user: root
    privileged : true
    restart: always       
    container_name: zabbix-server
    hostname: zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/server/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - ./zabbix/server/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - ./zabbix/agent/zabbix_agentd.psk:/etc/zabbix/zabbix_agentd.psk:ro
      - /var/log/rsyslog:/var/log/zabbix/rsyslog:rw
#     - ./zabbix/dockerdata/server/modules:/var/lib/zabbix/modules
#     - ./zabbix/dockerdata/server/enc:/var/lib/zabbix/enc
#     - ./zabbix/dockerdata/server/ssh_keys:/var/lib/zabbix/ssh_keys
#     - ./zabbix/dockerdata/server/ssl/certs:/var/lib/zabbix/ssl/certs
#     - ./zabbix/dockerdata/server/ssl/keys:/var/lib/zabbix/ssl/keys
#     - ./zabbix/dockerdata/server/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
#     - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
#     - ./zabbix/zabbix_server.conf:/etc/zabbix/zabbix_server.conf
    depends_on:
      - zabbix-postgres
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      PHP_TZ: ${timezone}

  zabbix-web:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-zabbix-web
      args:
        MISM_BULLSEQUANA_EDGE_VERSION: ${MISM_BULLSEQUANA_EDGE_VERSION}
    restart: always    
    container_name: zabbix-web
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      PHP_TZ: ${timezone}
    ports:
      - 4443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/ssl:/etc/ssl/nginx:ro
    user: root
    depends_on:
      - zabbix-server
    links:
      - zabbix-server:zabbix-server
  
  zabbix-agent:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-zabbix-agent
      args:
        MISM_BULLSEQUANA_EDGE_VERSION: ${MISM_BULLSEQUANA_EDGE_VERSION}
    ports:
      - 10050:10050
    expose: 
      - 10050
    user: root
    privileged : true
    depends_on:
      - zabbix-server
    restart: always
    container_name: zabbix-agent
    hostname: zabbix-agent
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      PHP_TZ: ${timezone}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/log/rsyslog:/var/log/zabbix/rsyslog:rw
      - ./zabbix/agent/zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf:Z
      - ./zabbix/agent/zabbix_agentd.psk:/etc/zabbix/zabbix_agentd.psk:Z
#      - ./zabbix/agent/zabbix_agentd.userparams.conf:/etc/zabbix/zabbix_agentd.d/zabbix_agentd.userparams.conf:Z
#      - ./zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
#      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
#      - ./zabbix/agent/modules:/var/lib/zabbix/modules
      - ./zabbix/agent/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
    links:
      - zabbix-server:zabbix-server

  zabbix-postgres:
    image: postgres:latest
    container_name: zabbix-postgres
    hostname: zabbix-postgres
    restart: unless-stopped
    env_file:
      - Dockerfiles/zabbix.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      PHP_TZ: ${timezone}
    ports:
      - 5555:5432
    expose: 
      - 5555
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/pgdata:/var/lib/postgresql/data/pgdata:Z
