version: '3.6'
services:

  awx_web:
    build: 
      context: .
      dockerfile: Dockerfile-awx_web
      args:
        mism_version: ${MISM_VERSION}
    container_name: awx_web
    depends_on:
      - rabbitmq
      - memcached
      - awx_postgres
    ports:
      - "443:8052"
    hostname: awx_web
    user: root
    restart: unless-stopped
    volumes:
      - ./ansible/playbooks:/var/lib/awx/projects:rw
      - ./ansible/inventory:/var/lib/awx/inventory:rw
      - ./ansible/inventory:/etc/ansible:rw
#      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml:/usr/lib/python2.7/site-packages/ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml
      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml:/usr/share/ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml
      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.py:/usr/lib/python2.7/site-packages/ansible/plugins/inventory/redfish_plugin_ansible_inventory.py
#      - ./ansible/plugins/inventory/:/usr/share/ansible/plugins/inventory
      - ./ansible/plugins/callback/ansible_stdout_compact_logger:/usr/share/ansible/plugins/callback/ansible_stdout_compact_logger
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc.py:/usr/lib/python2.7/site-packages/ansible/modules/remote_management/openbmc/atos_openbmc.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/lib/python2.7/site-packages/ansible/module_utils/atos_openbmc_utils.py:ro
      - ./ansible/awx-ssl:/var/lib/awx-ssl:rw
      - /:/host:ro
    environment:
      ANSIBLE_INVENTORY: /var/lib/awx/inventory
#      ANSIBLE_VAULT_PASSWORD_FILE: ansible_password.txt
#      ANSIBLE_INVENTORY_CACHE: yes
      TOWER_HOST: https://localhost:8052
      TOWER_USERNAME: mism
      TOWER_PASSWORD: mismpass
      TOWER_VERIFY_SSL: "false"
      TOWER_INSECURE: "true"
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      no_proxy: ${NO_PROXY}

  awx_task:
    build: 
      context: .
      dockerfile: Dockerfile-awx_task
      args:
        mism_version: ${MISM_VERSION}
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - awx_web
      - awx_postgres
    # command: ["/var/lib/awx/projects/add_playbooks.py", "/var/lib/awx/projects/playbooks.yml"]
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - ./ansible/playbooks:/var/lib/awx/projects:rw
      - ./ansible/inventory:/var/lib/awx/inventory:rw
      - ./ansible/inventory:/etc/ansible:rw
      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml:/usr/share/ansible/plugins/inventory/redfish_plugin_ansible_inventory.yml
      - ./ansible/plugins/inventory/redfish_plugin_ansible_inventory.py:/usr/lib/python2.7/site-packages/ansible/plugins/inventory/redfish_plugin_ansible_inventory.py
#      - ./ansible/plugins/inventory/:/usr/share/ansible/plugins/inventory
      - ./ansible/plugins/callback/ansible_stdout_compact_logger:/usr/share/ansible/plugins/callback/ansible_stdout_compact_logger
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc.py:/usr/lib/python2.7/site-packages/ansible/modules/remote_management/openbmc/atos_openbmc.py:ro
      - ./ansible/plugins/modules/remote_management/openbmc/atos_openbmc_utils.py:/usr/lib/python2.7/site-packages/ansible/module_utils/atos_openbmc_utils.py:ro
      - ./ansible/awx-ssl:/var/lib/awx-ssl:rw
      - /:/host:ro
    environment:
      ANSIBLE_INVENTORY: /var/lib/awx/inventory
#      ANSIBLE_VAULT_PASSWORD_FILE: ansible_password.txt
#      ANSIBLE_INVENTORY_CACHE: yes
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      no_proxy: ${NO_PROXY}


  rabbitmq:
    image: rabbitmq:3-management
    container_name: awx_rabbitmq
    restart: unless-stopped
    hostname: rabbitmq
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672    
    environment:
      RABBITMQ_DEFAULT_VHOST: awx
      RABBITMQ_DEFAULT_USER: mism
      RABBITMQ_DEFAULT_PASS: mismpass
      RABBITMQ_ERLANG_COOKIE: cookiemonster    

  memcached:
    image: memcached:alpine
    container_name: awx_memcached
    restart: unless-stopped

  awx_postgres:
    image: postgres:latest
    container_name: awx_postgres
    hostname: awx_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    expose: 
      - 5432
    volumes:
      - ./ansible/pgdata:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: mism
      POSTGRES_PASSWORD: mismpass
      POSTGRES_DB: mism
      PGDATA: /var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - awx_postgres
    user: root
    restart: unless-stopped
    ports:
      - 7070:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage:Z
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mism.com
      PGADMIN_DEFAULT_PASSWORD: mismpass


