---
- hosts: all
  connection: local
  name: System Inventory by url
  gather_facts: False

  tasks:
  
  - name: Create token from Redfish
    uri:
      url: https://{{ baseuri }}/redfish/v1/SessionService/Sessions
      method: POST
      validate_certs: no
      timeout: 30
      headers:
        Content-Type: "application/json"
      body_format: json
      status_code: 201
      body: 
        UserName: "{{ username }}"
        Password: "{{ password }}"
    register: result
    until: result.status == 201
    retries: "6"
    delay: "10"
    environment:
      no_proxy: localhost,127.0.0.1,{{baseuri}}
  
  - debug:
      var: result
      verbosity: 2
      
  - set_fact: 
      x_token: "{{ result.x_auth_token }}"

  - debug:
      var: x_token
      verbosity: 2

  - name: Get firmware inventory
    uri:
      url: https://{{ baseuri }}/redfish/v1/Systems
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_firmware_inventory
    environment:
      no_proxy: 127.0.0.1,{{baseuri}},localhost
      http_proxy: 
      https_proxy: 

  - set_fact:
      firmware_inventory_members: "{{ result_firmware_inventory.json.Members }}"

  - set_fact:
      firmware_inventory_name: "{{ result_firmware_inventory.json.Name }}"

  - debug:
      var: firmware_inventory_members
      verbosity: 2

  - debug:
      var: firmware_inventory_name
      verbosity: 2


