---
- hosts: all
  connection: local
  name: Chassis Inventory by url
  gather_facts: False

  tasks:
  
  - name: Create token from OpenBMC
    uri:
      url: https://{{ baseuri }}/login
      method: POST
      validate_certs: no
      timeout: 30
      headers:
       Content-Type: "application/json"
      body_format: json
      body: 
        username: "{{ username }}"
        password: "{{ password }}"
    register: result

  - set_fact: 
      x_token: "{{ result.json.token }}"

  - debug:
      var: x_token
      verbosity: 2

  - name: Get firmware inventory
    uri:
      url: https://{{ baseuri }}/redfish/v1/Chassis/Module0
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_firmware_inventory

  - set_fact:
      firmware_inventory: "{{ result_firmware_inventory.json.data }}"

  - debug:
      var: firmware_inventory
      verbosity: 2



