---
- hosts: all
  connection: local
  name: Manage System Power - Reboot BMC
  gather_facts: False
  vars_files:
    - /etc/ansible/vars/external_vars.yml
    - /etc/ansible/vars/passwords.yml

  tasks:

  - include_tasks: ../utils/utils_create_token.yml

  - include_tasks: ../utils/utils_reboot.yml   

  - name: Count down {{reboot_countdown}} minutes before checking reboot
    pause:
      minutes: "{{reboot_countdown}}"

  - include_tasks: ../utils/utils_check_reboot.yml   

