---
- hosts: all
  connection: local
  name: Disable Power Cap
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_EXTERNAL_VARS }}"
    - "{{ ANSIBLE_PASSWORDS }}"

  tasks:

  - include_tasks: ../utils/utils_create_token.yml

  - name: disable Power Cap
    uri:
      url: https://{{ baseuri }}/xyz/openbmc_project/control/host0/power_cap/attr/PowerCapEnable
      method: PUT
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
      body_format: json
      body: 
        data: false
    register: result_disable_power_cap
