---
- hosts: all
  connection: local
  name: Disable Power Cap
  gather_facts: False
  vars_files:
    - /var/lib/awx/projects/vars/external_vars.yml
    - /var/lib/awx/projects/vars/passwords.yml

  tasks:

  - include_tasks: ../utils/utils_create_token.yml

  - name: set Power Cap
    uri:
      url: https://{{ baseuri }}/xyz/openbmc_project/control/host0/power_cap/attr/PowerCap
      method: PUT
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
      body_format: json
      body: 
        data: "{{ power_cap }}"
    register: result_power_cap

  - name: disable Power Cap
    uri:
      url: https://{{ baseuri }}/xyz/openbmc_project/control/host0/power_cap/attr/PowerCapEnable
      method: PUT
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
      body_format: json
      body: 
        data: false
    register: result_disable_power_cap
