---
# Update and Activate playbooks use these variables if needed
forceoff: True
reboot: True

# Count down before checking a successfull reboot in MINUTES
reboot_countdown: 3
# Count down before checking a successfull for power on/off in SECONDS
poweron_countdown: 15
poweroff_countdown: 15

# Set a path to a Bull Technical State file
technical_state_path: /mnt

# Define rsyslog ip and port
# default rsyslog port is 514
#rsyslog_server_ip: <here rsyslog ip address>
rsyslog_server_port: 514

# Define a power capability
#power_cap: 500

# File to upload with update_firmware_from_file.yml playbook
#file_to_upload: /host/mnt/Resources/Firmware_and_related_documents/BIOS/<here your file .tar or .gzip>

# To delete a ready image : uncomment and fill the Purpose and the Version
#purpose_to_delete: BMC
#version_to_delete: 00.00.0000

