---
- hosts: all
  connection: local
  name: Enable User
  gather_facts: False

  tasks:

  - name: Enable user
    redfish_command:
      category: Accounts
      command: EnableUser
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
      id: "{{ id }}"
