---
- hosts: localhost
  name: Atos Python script - Redfish utils
  gather_facts: False

  tasks:
  - name: Get FWs of TS nodes
    xml:
      path: /tmp
      xpath: /TECHNICAL_STATE/FM_LIST/FW
    debug: msg="reading technical state"
    delegate_to: 127.0.0.1
    run_once: true
    register: FWs

  - debug:
      var: FWs.count

  - name: Atos Utilitaires Python
      script: redfish_utils.py
      when: item.name == "lo0"
    register: result

  - name: print result
    debug: msg="Result from utils {{result.stdout}}"
    delegate_to: 127.0.0.1
    run_once: true
