---
- hosts: all
  name: Firmware Inventory Active
  connection: local
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_EXTERNAL_VARS }}"
    - "{{ ANSIBLE_PASSWORDS }}"

  tasks:

  - include_tasks: ../utils/utils_create_token.yml

  - include_tasks: ../utils/utils_firmware_inventory.yml

  - name: render Active Firmwares
    debug:
      msg: "Active {{ item.value.Purpose }} - {{ item.value.Version }} ({{ item.key }})"
    when: item.value.Activation is defined and item.value.Activation == "xyz.openbmc_project.Software.Activation.Activations.Active"
    with_dict: "{{ firmware_inventory }}"

