---
- hosts: all
  connection: local
  name: Get Boot Mode
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_EXTERNAL_VARS }}"
    - "{{ ANSIBLE_PASSWORDS }}"

  tasks:
  - include_tasks: ../utils/utils_create_token.yml

  - name: get boot mode
    uri:
      url: https://{{ baseuri }}/xyz/openbmc_project/control/host0/boot/one_time/attr/BootMode
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_boot_mode

  - set_fact:
      boot_mode: "{{ result_boot_mode.json.data }}"

  - name: Bios Boot Mode
    debug:
      var: boot_mode

