---
- hosts: all
  name: Reboot BMC
  connection: local
  gather_facts: False
  vars_files:
    - /var/lib/awx/projects/vars/passwords.yml

  tasks:
  - include_tasks: ../utils/utils_create_token.yml

  - name: reboot BMC
    uri:
      url: https://{{ baseuri }}/xyz/openbmc_project/state/bmc0/attr/RequestedBMCTransition
      method: PUT
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
        Content-Type: "application/json"
      body:
        data: xyz.openbmc_project.State.BMC.Transition.Reboot
      body_format: json
    register: result_reboot_bmc



