---
- hosts: all
  name: Firmware Update
  connection: local
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_EXTERNAL_VARS }}"
    - "{{ ANSIBLE_PASSWORDS }}"

  tasks:
  - name: validate technical_state_path variable
    assert:
      that:
        - technical_state_path is defined
      fail_msg: "The variable technical_state_path is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable technical_state_path is defined"
    run_once: true

  - debug:
      msg: "technical_state_path is {{ technical_state_path }}"
    when: technical_state_path is defined
    run_once: true

  - include_tasks: ../utils/utils_create_token.yml

  - include_tasks: ../utils/utils_firmware_inventory.yml

  - include_tasks: ../utils/utils_evaluate_firmware_update.yml

  - name: render active firmware
    debug:
      msg: "Active firmware = {{ item.key }} as {{ item.value.Purpose }}-{{ item.value.Version }}"
    with_dict: "{{ firmware_inventory }}"
    when: item.value.Activation is defined and item.value.Activation == "xyz.openbmc_project.Software.Activation.Activations.Active"

  - include_tasks: ../utils/utils_upload_firmwares.yml

  - include_tasks: ../utils/utils_firmware_inventory.yml

  - name: render Uploaded Firmwares
    debug:
      msg: "Ready firmware = {{ item.key }} as {{ item.value.Purpose }}-{{ item.value.Version }}"
    when: item.value.Activation is defined and item.value.Activation == "xyz.openbmc_project.Software.Activation.Activations.Ready"
    with_dict: "{{ firmware_inventory }}"

