---
- hosts: all
  connection: local
  name: Manage System Power - Graceful restart
  gather_facts: False

  tasks:

  - name: Restart system power gracefully
    redfish_command:
      category: Systems
      command: PowerGracefulRestart
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
