---
  - name: Define timestamp
    set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    run_once: true

  - name: Define file to place results
#    set_fact: template={{rootdir}}/{{host}}_{{datatype}}_{{timestamp}}
    set_fact: template={{rootdir}}/last_{{datatype}}

  - name: Create dropoff directory for host
    file:
      path: "{{ rootdir }}"
      state: directory
