---
- hosts: all
  connection: local
  name: Sensor Inventory
  gather_facts: False

  tasks:
  - name: Publish result to rabbitmq
    rabbitmq_publish:
      host: rabbitmq
      proto: amqp
      exclusive: false
      port: 5672
      vhost: awx
      durable: true
      username: guest
      password: awxpass
      body: "Hello world from ansible module rabbitmq_publish"
      queue: 'redfishmq'
      content_type: "text/plain"

